Fix trash

diff --git a/plugins/macos/functions/trash b/plugins/macos/functions/trash
--- a/plugins/macos/functions/trash
+++ b/plugins/macos/functions/trash
@@ -1,22 +1,36 @@
 #!/bin/zsh
 ##? trash - add files to trash
-function trash {
+#function trash {
 
-local -a files=()
+emulate -L zsh
+setopt local_options extended_glob
+
+if (( $# == 0 ))
+  echo >&2 "Usage: trash <files>"
+  return 1
+fi
+
+if [[ $OSTYPE != darwin* ]]; then
+  print -ru2 -- "trash: macOS not detected."
+  return 1
+fi
+
 local file
-for file in $@; do
+local -a files
+for file in $@
   if [[ -e $file ]]; then
     files+=("the POSIX file \"${file:A}\"")
   else
-    print -u 2 "trash: No such file or directory '$files'."
+    print -ru2 -- "trash: No such file or directory '$file'."
     return 1
   fi
-done
-
-if (( $#files == 0 )); then
-  print -u 2 'usage: trash <files...>'
-  return 64  # match rm's return code
 fi
 
-osascript 2>&1 >/dev/null -e "tell app \"Finder\" to move { ${(j., .)files} } to trash"
-}
+if (( $#files == 0 )); then
+  print -ru2 -- 'usage: trash <files...>'
+  return 64 # match rm's return code
+fi
+
+osascript 2>&1 >/dev/null -e "tell app \"Finder\" to move { "${(pj., .)files}" } to trash"
+
+#}
